// Code generated by mockery v2.53.6. DO NOT EDIT.

package ping

import (
	context "context"
	entity "myAPI/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockPingRepository is an autogenerated mock type for the PingRepository type
type MockPingRepository struct {
	mock.Mock
}

type MockPingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingRepository) EXPECT() *MockPingRepository_Expecter {
	return &MockPingRepository_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function with given fields: req
func (_m *MockPingRepository) CreateMessage(req *entity.PingDto) *entity.PingDto {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *entity.PingDto
	if rf, ok := ret.Get(0).(func(*entity.PingDto) *entity.PingDto); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PingDto)
		}
	}

	return r0
}

// MockPingRepository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockPingRepository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - req *entity.PingDto
func (_e *MockPingRepository_Expecter) CreateMessage(req interface{}) *MockPingRepository_CreateMessage_Call {
	return &MockPingRepository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", req)}
}

func (_c *MockPingRepository_CreateMessage_Call) Run(run func(req *entity.PingDto)) *MockPingRepository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PingDto))
	})
	return _c
}

func (_c *MockPingRepository_CreateMessage_Call) Return(_a0 *entity.PingDto) *MockPingRepository_CreateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPingRepository_CreateMessage_Call) RunAndReturn(run func(*entity.PingDto) *entity.PingDto) *MockPingRepository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMessage provides a mock function with given fields: ctx
func (_m *MockPingRepository) FetchMessage(ctx context.Context) ([]entity.PingDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessage")
	}

	var r0 []entity.PingDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.PingDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.PingDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PingDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPingRepository_FetchMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessage'
type MockPingRepository_FetchMessage_Call struct {
	*mock.Call
}

// FetchMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPingRepository_Expecter) FetchMessage(ctx interface{}) *MockPingRepository_FetchMessage_Call {
	return &MockPingRepository_FetchMessage_Call{Call: _e.mock.On("FetchMessage", ctx)}
}

func (_c *MockPingRepository_FetchMessage_Call) Run(run func(ctx context.Context)) *MockPingRepository_FetchMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPingRepository_FetchMessage_Call) Return(_a0 []entity.PingDto, _a1 error) *MockPingRepository_FetchMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPingRepository_FetchMessage_Call) RunAndReturn(run func(context.Context) ([]entity.PingDto, error)) *MockPingRepository_FetchMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPingRepository creates a new instance of MockPingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingRepository {
	mock := &MockPingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
