// Code generated by mockery v2.53.6. DO NOT EDIT.

package ping

import (
	context "context"
	entity "myAPI/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockPingService is an autogenerated mock type for the PingService type
type MockPingService struct {
	mock.Mock
}

type MockPingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingService) EXPECT() *MockPingService_Expecter {
	return &MockPingService_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function with given fields: req
func (_m *MockPingService) CreateMessage(req *entity.PingDto) *entity.PingDto {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *entity.PingDto
	if rf, ok := ret.Get(0).(func(*entity.PingDto) *entity.PingDto); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PingDto)
		}
	}

	return r0
}

// MockPingService_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockPingService_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - req *entity.PingDto
func (_e *MockPingService_Expecter) CreateMessage(req interface{}) *MockPingService_CreateMessage_Call {
	return &MockPingService_CreateMessage_Call{Call: _e.mock.On("CreateMessage", req)}
}

func (_c *MockPingService_CreateMessage_Call) Run(run func(req *entity.PingDto)) *MockPingService_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.PingDto))
	})
	return _c
}

func (_c *MockPingService_CreateMessage_Call) Return(_a0 *entity.PingDto) *MockPingService_CreateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPingService_CreateMessage_Call) RunAndReturn(run func(*entity.PingDto) *entity.PingDto) *MockPingService_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with given fields: ctx
func (_m *MockPingService) GetMessage(ctx context.Context) ([]entity.PingDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 []entity.PingDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.PingDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.PingDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PingDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPingService_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockPingService_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPingService_Expecter) GetMessage(ctx interface{}) *MockPingService_GetMessage_Call {
	return &MockPingService_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx)}
}

func (_c *MockPingService_GetMessage_Call) Run(run func(ctx context.Context)) *MockPingService_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPingService_GetMessage_Call) Return(_a0 []entity.PingDto, _a1 error) *MockPingService_GetMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPingService_GetMessage_Call) RunAndReturn(run func(context.Context) ([]entity.PingDto, error)) *MockPingService_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPingService creates a new instance of MockPingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingService {
	mock := &MockPingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
