// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"
	entity "myAPI/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockService) Create(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockService_Expecter) Create(ctx interface{}, req interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *entity.UserDto, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, req
func (_m *MockService) Delete(ctx context.Context, req *entity.UserDto) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockService_Expecter) Delete(ctx interface{}, req interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, *entity.UserDto) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockService) FindAll(ctx context.Context) ([]entity.UserDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.UserDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.UserDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) FindAll(ctx interface{}) *MockService_FindAll_Call {
	return &MockService_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockService_FindAll_Call) Run(run func(ctx context.Context)) *MockService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_FindAll_Call) Return(_a0 []entity.UserDto, _a1 error) *MockService_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.UserDto, error)) *MockService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, req
func (_m *MockService) FindByEmail(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockService_Expecter) FindByEmail(ctx interface{}, req interface{}) *MockService_FindByEmail_Call {
	return &MockService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, req)}
}

func (_c *MockService_FindByEmail_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockService_FindByEmail_Call) Return(_a0 *entity.UserDto, _a1 error) *MockService_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_FindByEmail_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: ctx, req
func (_m *MockService) FindById(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockService_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockService_Expecter) FindById(ctx interface{}, req interface{}) *MockService_FindById_Call {
	return &MockService_FindById_Call{Call: _e.mock.On("FindById", ctx, req)}
}

func (_c *MockService_FindById_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockService_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockService_FindById_Call) Return(_a0 *entity.UserDto, _a1 error) *MockService_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_FindById_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockService_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function with given fields: ctx, fromID, toID, amount
func (_m *MockService) Transfer(ctx context.Context, fromID string, toID string, amount int) error {
	ret := _m.Called(ctx, fromID, toID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, fromID, toID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type MockService_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID string
//   - toID string
//   - amount int
func (_e *MockService_Expecter) Transfer(ctx interface{}, fromID interface{}, toID interface{}, amount interface{}) *MockService_Transfer_Call {
	return &MockService_Transfer_Call{Call: _e.mock.On("Transfer", ctx, fromID, toID, amount)}
}

func (_c *MockService_Transfer_Call) Run(run func(ctx context.Context, fromID string, toID string, amount int)) *MockService_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockService_Transfer_Call) Return(_a0 error) *MockService_Transfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Transfer_Call) RunAndReturn(run func(context.Context, string, string, int) error) *MockService_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockService) Update(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockService_Expecter) Update(ctx interface{}, req interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *entity.UserDto, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
