// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"
	entity "myAPI/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockRepository) Create(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockRepository_Expecter) Create(ctx interface{}, req interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *entity.UserDto, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, req
func (_m *MockRepository) Delete(ctx context.Context, req *entity.UserDto) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockRepository_Expecter) Delete(ctx interface{}, req interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, *entity.UserDto) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockRepository) FindAll(ctx context.Context) ([]entity.UserDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.UserDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.UserDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) FindAll(ctx interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(_a0 []entity.UserDto, _a1 error) *MockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.UserDto, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, req
func (_m *MockRepository) FindByEmail(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockRepository_Expecter) FindByEmail(ctx interface{}, req interface{}) *MockRepository_FindByEmail_Call {
	return &MockRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, req)}
}

func (_c *MockRepository_FindByEmail_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockRepository_FindByEmail_Call) Return(_a0 *entity.UserDto, _a1 error) *MockRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: ctx, req
func (_m *MockRepository) FindById(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockRepository_Expecter) FindById(ctx interface{}, req interface{}) *MockRepository_FindById_Call {
	return &MockRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, req)}
}

func (_c *MockRepository_FindById_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockRepository_FindById_Call) Return(_a0 *entity.UserDto, _a1 error) *MockRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindById_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdForUpdate provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindByIdForUpdate(ctx context.Context, id string) (*entity.UserDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdForUpdate")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.UserDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.UserDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByIdForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdForUpdate'
type MockRepository_FindByIdForUpdate_Call struct {
	*mock.Call
}

// FindByIdForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByIdForUpdate(ctx interface{}, id interface{}) *MockRepository_FindByIdForUpdate_Call {
	return &MockRepository_FindByIdForUpdate_Call{Call: _e.mock.On("FindByIdForUpdate", ctx, id)}
}

func (_c *MockRepository_FindByIdForUpdate_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByIdForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByIdForUpdate_Call) Return(_a0 *entity.UserDto, _a1 error) *MockRepository_FindByIdForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByIdForUpdate_Call) RunAndReturn(run func(context.Context, string) (*entity.UserDto, error)) *MockRepository_FindByIdForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req
func (_m *MockRepository) Update(ctx context.Context, req *entity.UserDto) (*entity.UserDto, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.UserDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) (*entity.UserDto, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserDto) *entity.UserDto); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserDto) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UserDto
func (_e *MockRepository_Expecter) Update(ctx interface{}, req interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, req *entity.UserDto)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserDto))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *entity.UserDto, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.UserDto) (*entity.UserDto, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function with given fields: ctx, id, newBalance
func (_m *MockRepository) UpdateBalance(ctx context.Context, id string, newBalance int) error {
	ret := _m.Called(ctx, id, newBalance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, id, newBalance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockRepository_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newBalance int
func (_e *MockRepository_Expecter) UpdateBalance(ctx interface{}, id interface{}, newBalance interface{}) *MockRepository_UpdateBalance_Call {
	return &MockRepository_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, id, newBalance)}
}

func (_c *MockRepository_UpdateBalance_Call) Run(run func(ctx context.Context, id string, newBalance int)) *MockRepository_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_UpdateBalance_Call) Return(_a0 error) *MockRepository_UpdateBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateBalance_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRepository_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
