// Code generated by mockery v2.53.6. DO NOT EDIT.

package activity

import (
	context "context"
	entity "myAPI/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, log
func (_m *MockService) Create(ctx context.Context, log *entity.ActivityLogDto) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ActivityLogDto) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.ActivityLogDto
func (_e *MockService_Expecter) Create(ctx interface{}, log interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, log *entity.ActivityLogDto)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ActivityLogDto))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 error) *MockService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, *entity.ActivityLogDto) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
